### ISSUE TITLE
Brave reporting: CodeSignatureVerifier: hdiutil imageinfo error hdiutil: imageinfo failed - image not recognised

### ISSUE THREAD

**Issue by jby** [autopkg/apettinen-recipes#27] opened 2020-09-22 11:21 UTC
The last week Brave.munki has been giving me these errors:

```autopkg run -v local.munki.Brave
Processing local.munki.Brave...
URLDownloader
URLDownloader: Item at URL is unchanged.
URLDownloader: Using existing /Users/jonasb/Library/AutoPkg/Cache/local.munki.Brave/downloads/Brave.dmg
EndOfCheckPhase
CodeSignatureVerifier
CodeSignatureVerifier: hdiutil imageinfo error hdiutil: imageinfo failed - image not recognised
 with image /Users/jonasb/Library/AutoPkg/Cache/local.munki.Brave/downloads/Brave.dmg.
/Users/jonasb/Library/AutoPkg/Cache/local.munki.Brave/downloads/Brave.dmg is not mounted
Failed.
Receipt written to /Users/jonasb/Library/AutoPkg/Cache/local.munki.Brave/receipts/local.munki-receipt-20200922-131717.plist

The following recipes failed:
    local.munki.Brave
        Error in local.munki.Brave: Processor: CodeSignatureVerifier: Error: /Users/jonasb/Library/AutoPkg/Cache/local.munki.Brave/downloads/Brave.dmg is not mounted

Nothing downloaded, packaged or imported.

**Comment by jby** [comment] 2020-09-22 11:35
Removed the downloaded file and re-ran autopkg still though `image not recognised`

**Comment by jby** [comment] 2020-09-22 11:43
Ok, after downloading it manually I realized that you're downloading the pkg into a dmg-file for some strange reason, the download URL in brave.download.recipe **does** point to the dmg-download, but somehow the pkg is downloaded instead...

**Comment by jby** [comment] 2020-09-22 11:45
Or maybe it's simply that they've renamed Brave.dmg into Brave-browser.dmg that's causing this problem...

**Comment by jby** [comment] 2020-09-22 11:49
Nope, `wget https://laptop-updates.brave.com/latest/osx` still produces a pkg and not a dmg...
But - going to https://laptop-updates.brave.com/latest/osx in Safari downloads Brave-browser.dmg which **is** a dmg...

**Comment by apettinen** [comment] 2020-09-22 12:47
Thanks for reporting this so nicely! :) I will take a look and adjust the recipe accordingly!

**Comment by apettinen** [comment] 2020-09-22 12:56
Alright, this get's a bit weird: I got a dmg via the autopkg recipe. Will investigate more.

**Comment by apettinen** [comment] 2020-09-22 14:09
Seems to be a kind-of Duplicate of #20 but not really. The reason behind this error is that the (Varnish/Fastly) cache Brave is using resolves to either https://brave-browser-downloads.s3.brave.com/latest/Brave-Browser.dmg   or https://referrals.brave.com/latest/Brave-Browser.pkg  depending on which cache node you hit.

Decided to switch to Sparkel AppCast. This issue is fixed by: https://github.com/autopkg/apettinen-recipes/commit/6a331bd9fcb6d624dda23cc6813c0ce40b884b78

**Closed by apettinen** 2020-09-22 14:09 UTC
